# Generated by Django 4.1.4 on 2023-01-09 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_about_alter_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
