# Generated by Django 4.1.4 on 2023-01-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_staff_position_alter_author_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to='staffs'),
        ),
    ]
