# Generated by Django 4.1.4 on 2023-01-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_staff_position_about_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
