# Generated by Django 4.1.4 on 2023-01-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
