# Generated by Django 4.1.4 on 2023-01-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_staff_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(null=True, upload_to='staffs'),
        ),
    ]
