# Generated by Django 4.1.4 on 2023-01-10 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_tags',
            field=models.CharField(editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
