# Generated by Django 4.1.4 on 2023-01-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_post_excerpt_alter_post_image_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(editable=False, max_length=120),
        ),
    ]
