# Generated by Django 4.1.4 on 2023-01-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_siteusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteusers',
            name='date_of_birth',
        ),
    ]
