# Generated by Django 4.1.4 on 2023-01-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_siteusers_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_pic',
            field=models.ImageField(default='default_pfp.png', null=True, upload_to=None),
        ),
    ]
