# Generated by Django 4.1.5 on 2023-01-28 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_about_about_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(200), django.core.validators.MaxLengthValidator(4000)]),
        ),
    ]
