# Generated by Django 4.1.5 on 2023-01-28 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Coming soon', validators=[django.core.validators.MinLengthValidator(270), django.core.validators.MaxLengthValidator(4000)]),
        ),
    ]
