# Generated by Django 4.1.5 on 2023-01-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='number_of_comment',
        ),
    ]
