# Generated by Django 4.1.5 on 2023-01-31 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_remove_post_excerpt_remove_post_number_of_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Coming soon...', validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(6500)]),
        ),
    ]
