# Generated by Django 4.1.5 on 2023-02-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='default_pfp.jpg', upload_to='staffs'),
        ),
    ]
