# Generated by Django 4.1.5 on 2023-02-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_alter_comment_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_pic',
            field=models.ImageField(default='default_pfp_img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='default_pfp_img.jpg', upload_to='staffs'),
        ),
    ]
