# Generated by Django 4.1.5 on 2023-02-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_alter_comment_user_pic_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_pic',
            field=models.ImageField(default='default_pfp.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_post_img.jpg', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='default_pfp.png', upload_to='staffs'),
        ),
    ]
